name: Node.js CI

on: [push, pull_request, workflow_dispatch]

#on:
#  push:
#    branches: [ "*" ]
#  pull_request:
#    branches: [ "*" ]
#  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: ['4.2', '4.4', '5.0']

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    #- name: Start MongoDB
    #  uses: supercharge/mongodb-github-action@1.7.0
    #  with:
    #    mongodb-version: ${{ matrix.mongodb-version }}

    - name: Build backend
      run: npm install
      working-directory: ./backend

    - name: Test backend
      run: npm test
      working-directory: ./backend
